--[[
Lasanha || TEVEZ
by r7pha (discord)
https://discord.gg/SYNBSkvkEN
--]]
if setclipboard then setclipboard 'https://discord.gg/XrzB5JPC'; end
game.Players.LocalPlayer:Kick("Este script está em rewrite, portanto, indisponível no momento. Porém, você pode entrar em nosso servidor do Discord para receber atualizações e, assim que estiver pronto, notificaremos você! Invite: https://discord.gg/XrzB5JPC (copiado para clipboard)");
